### ISSUE TITLE
Error After first login and change of the  Vertical Level 

### ISSUE THREAD

**Issue by pjoscha** [fodinabor/CT-Organigram#1]
Dear @fodinabor, 
i found an issue with in the first login and change of the  Vertical Level.
the following message appears:
>Encrypted data changed. Not using it.

after browser restart the issue is restorable.

Using the E-Mail login.
Same problem on different Browsers (Firefox/Internet Explorer/Chrome)

**Comment by fodinabor** [comment]
@pjoscha: I found a bug concerning cookie retention / deletion, that I fixed, which made the problem disappear for me. Can you confirm this fix is working?

**Comment by pjoscha** [comment]
Dear @fodinabor, looking good.
Big thanks for the fast help.

**Comment by fodinabor** [comment]
Sure, security and stability are quite important to me ;-)
