### ISSUE TITLE
Data could not been fetched

### ISSUE THREAD

**Issue by pjoscha** [fodinabor/CT-Organigram#2]
Dear @fodinabor,
not sure if this is an issue but currently only the Admin user is able to see the organigram.
All other users recieve an issue that "data could not been fetched", i asume that there is some rights are missing. If this is the case, do you know which rights are needed to gain access?
The login at all works flawless.

**Comment by fodinabor** [comment]
please see 2bdf788

**Comment by pjoscha** [comment]
Working fine, thanks.
