### ISSUE TITLE
It is currently not usable.

### ISSUE THREAD

**Issue by pjoscha** [fodinabor/CT-Organigram#3]
the login is no longer possible on my side, also the code is no longer getting data from Churchtools, are you able to update this project it was such a great tool

**Comment by fodinabor** [comment]
Hi,
Yes, data ain't fetched as it should be. I won't be able to look into it this week, will try to revive it soon, though.
Although I'm obviously also very happy if anybody else chips in ;-)

**Comment by pjoscha** [comment]
Thanks for the Update.Am 31.01.2023 07:21 schrieb fodinabor ***@***.***>:
Hi,
Yes, data ain't fetched as it should be. I won't be able to look into it this week, will try to revive it soon, though.
Although I'm obviously also very happy if anybody else chips in ;-)

**Comment by fodinabor** [comment]
Fixed by [118d201](https://github.com/fodinabor/CT-Organigram/commit/118d20194d0bae5ba009328510eb368fe0cd5ef7).
Enjoy :)
