### ISSUE TITLE
News Error since Last Churchtools release

### ISSUE THREAD

**Issue by pjoscha** [fodinabor/CT-Organigram#4]
Hi since the Last Release the Organigramm is No konger working.
Can you pleased have a Look

Best regards

**Comment by fodinabor** [comment]
Should be fixed now 👍🏼

**Comment by pjoscha** [comment]
Perfekt, thanksAm 01.05.2023 21:34 schrieb fodinabor ***@***.***>:
Should be fixed now 👍🏼
